# Generated by Django 5.0.1 on 2024-01-04 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default='Man', max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
